### ISSUE TITLE
REPORTE TEXBOX

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IMA-G#2]
[TexBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IMA-G/files/6353610/TexBox.pdf)

**Comment by MariaC232** [comment]
Calificación: 20
Muy buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
